name: pyro311
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.10.8
  - numpy=1.26.4
  - pandas=2.3.3
  - pip=25.3
  - python=3.11.14
  - pytorch=2.5.1
  - scikit-learn=1.3.1
  - scipy=1.16.3
  - seaborn=0.13.2
  - torchvision=0.20.1
  - pip:
      - graphviz==0.21
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - sympy==1.13.1
      - tqdm==4.67.1
      - visdom==0.2.4
